name: Deploy stats lambda

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 👇 Esto hace que todos los `run:` se ejecuten dentro del módulo
    defaults:
      run:
        working-directory: lambda-modules/module-3-stats

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test -- --watch=false

      - name: Build
        run: npm run build

      - name: Package
        run: npm run package
